# Generated by Django 4.2.7 on 2023-11-08 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('status', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ctrol', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=80)),
                ('ap_pat', models.CharField(max_length=80)),
                ('ap_mat', models.CharField(max_length=80)),
                ('status', models.SmallIntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alumnos.carreras')),
            ],
        ),
    ]
